language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

env:
  - DB=postgres DB_VERSION=9.6
  - DB=postgres DB_VERSION=10
  - DB=postgres DB_VERSION=11

services:
  - docker

before_install:
  - docker run --name postgres -p 127.0.0.1:15432:5432 -e POSTGRES_USER=efureev -e POSTGRES_DB=test -d postgres:${DB_VERSION}
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

before_script:
  - psql -c 'create database tests;' -U postgres
  - composer install

script:
  - locale
  - php -r 'echo setlocale(LC_CTYPE,0);'
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml

after_script:
  - ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer
